### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Misat11** [ScreamingSandals/BedWars#19]
TODO list (from discord):
* [x] look of spawner holograms
* [x] kill players when he's on edge of the map
* [x] Countdown to next spawn of resource
* [x] max spawned resources of spawner
* [x] show/hide price lore for item
* [x] look of price lore
* [x] head name for villager shop
* [x] premium commands force start, force join (from #23)
* [x] config for order and text on sign (from #23) 
* [x] **support for another holographic system or own holographic system, because holographic displays is not working correctly in some cases**
* [x] breakable blocks
* [x] Add option to link spawner to team
* [x] Join to already running arena as spectator

**Comment by notfoundname** [comment]
Join to already running arena as spectator :)
