### ISSUE TITLE
[0.3.x] TODO

### ISSUE THREAD

**Issue by Misat11** [ScreamingSandals/BedWars#76]
TODO list (from discord):

- [ ] Implement alll bugfixes and features present in 0.x.x
- [ ] upgrades after time (We have API for Upgrades)
- [x] keep specific item after respawn
- [x] **Rewrite scoreboard system for each player generation, add some placeholders and add support for PAPI**
- [ ] Do all feature requests with label 1.x.x
- [ ] Add SBA functionality into the main plugin
- [x] *Find some new developers*

**Comment by linusstretchtips** [comment]
yall forgot bout this checklist or what?

**Comment by Misat11** [comment]
Closed because we use trello instead.
